//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace  YTrailerWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YTask
    {
        public YTask()
        {
            this.PromoRequests = new HashSet<PromoRequest>();
        }
    
        public int Id { get; set; }
        public string YouTubeUrl { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public bool isHandled { get; set; }
        public string State { get; set; }
    
        public virtual YTitle YTitle { get; set; }
        public virtual ICollection<PromoRequest> PromoRequests { get; set; }
    }
}
